import { PortfolioItem } from './types';

/**
 * The portfolio, as bundled with the site.
 *
 * Normally the live portfolio is served from the InsForge `portfolio_projects`
 * table via `src/utils/insforge/portfolio.ts`, and this array is the seed input
 * for `npm run seed:portfolio` (see scripts/seed-portfolio.ts).
 *
 * It is ALSO the offline fallback: if the backend is unreachable or returns no
 * published rows, the site renders this list instead of an empty page. Every
 * screenshot is committed to `public/portfolio/`, so the portfolio keeps
 * working with no backend at all.
 *
 * Every entry below is a real, live client site. Do not add speculative or
 * example work here — it is customer-facing.
 *
 * When you add work in the admin, add it here too (or re-export) so the
 * fallback stays in step.
 */
export const PORTFOLIO_ITEMS: PortfolioItem[] = [
  {
    id: 'atozfacility',
    title: 'AtoZ Facility Management',
    category: 'Corporate',
    description: 'Hospital staffing and manpower services site for a Barnala, Punjab firm supplying verified nursing, ward, housekeeping and security staff to hospitals and institutions since 2010.',
    highlight: 'Trust-First Staffing',
    imageUrl: '/portfolio/atozfacility.webp',
    techStack: ['Next.js', 'React', 'Lead Capture', 'Local SEO'],
    websiteUrl: 'https://www.atozfacility.com/',
  },
  {
    id: 'jfmgroup',
    title: 'JFM Group',
    category: 'Corporate',
    description: 'Security and facility management company site for a Kolkata group offering guards, housekeeping, manpower, nursing and sanitation services across West Bengal since 2008.',
    highlight: 'Services Under One Roof',
    imageUrl: '/portfolio/jfmgroup.webp',
    techStack: ['Next.js', 'React', 'Quote Requests', 'Local SEO'],
    websiteUrl: 'https://jfmgroup.in/',
  },
  {
    id: 'kavitakabira',
    title: 'Kavita Kabira Wellness Clinic',
    category: 'Corporate',
    description: 'A calm, editorial site for a Gurgaon psychologist offering psychotherapy, counselling, wellness coaching and transformational workshops, in person and online.',
    highlight: 'Warm & Reassuring',
    imageUrl: '/portfolio/kavitakabira.webp',
    techStack: ['Next.js', 'React', 'Appointment Booking', 'SEO Optimization'],
    websiteUrl: 'https://www.kavitakabira.com/',
  },
  {
    id: 'rentzora',
    title: 'Rentzora',
    category: 'E-Commerce',
    description: 'An online rental marketplace for bridal, temple and fine jewellery from verified owners across India, with video-confirmed condition, refundable deposits and insured delivery.',
    highlight: 'Rental Marketplace',
    imageUrl: '/portfolio/rentzora.webp',
    techStack: ['Next.js', 'React', 'Marketplace Listings', 'Owner Onboarding'],
    websiteUrl: 'https://www.rentzora.in/',
  },
  {
    id: 'mastermocks',
    title: 'Master Mocks',
    category: 'SaaS',
    description: 'A performance-based mock test platform for Banking and Insurance exams, with exam-level mocks, detailed solutions and cashback rewards for top performers.',
    highlight: 'Rewarded Practice',
    imageUrl: '/portfolio/mastermocks.webp',
    techStack: ['Next.js', 'React', 'Razorpay', 'Mock Test Engine'],
    websiteUrl: 'https://www.mastermocks.in/',
  },
  {
    id: 'omoora',
    title: 'Omoora Art & Design Studio',
    category: 'Corporate',
    description: 'Site for a Gurugram art academy running since 2010, covering art classes for kids and adults, mandala art, a fine-arts diploma, energy healing and tarot guidance.',
    highlight: 'A Creative Awakening',
    imageUrl: '/portfolio/omoora.webp',
    techStack: ['Next.js', 'React', 'Demo Booking', 'Local SEO'],
    websiteUrl: 'https://www.omoora.in/',
  },
  {
    id: 'theselvedge',
    title: 'The Selvedge',
    category: 'Corporate',
    description: 'A premium B2B denim manufacturing showcase for private labelling, OEM production and bespoke made-to-measure denim for global brands.',
    highlight: 'Crafted Denim',
    imageUrl: '/portfolio/theselvedge.webp',
    techStack: ['Next.js', 'React', 'B2B Enquiries', 'Product Showcase'],
    websiteUrl: 'https://www.theselvedge.co.in/',
  },
  {
    id: 'groomore',
    title: 'Gromore Investment',
    category: 'Corporate',
    description: 'A goal-first investment site helping families across India plan for retirement, education and long-term goals with written, goal-linked investment schemes.',
    highlight: 'Goal-Led Clarity',
    imageUrl: '/portfolio/groomore.webp',
    techStack: ['Next.js', 'React', 'Consultation Booking', 'SEO Optimization'],
    websiteUrl: 'https://www.groomore.in/',
  },
  {
    id: 'laikenengineering',
    title: 'Laiken Engineering Company',
    category: 'Corporate',
    description: 'Industrial component supplier site for motion cables, drag chains, Siemens PLCs and Siemens and Yaskawa AC drives, built around sending a specification and getting a written quote.',
    highlight: 'Spec-to-Quote Flow',
    imageUrl: '/portfolio/laikenengineering.webp',
    techStack: ['Next.js', 'React', 'Product Catalog', 'Quote Requests'],
    websiteUrl: 'https://laikenengineering.com/',
  },
  {
    id: 'saanshikaethnics',
    title: 'Saanshika Ethnics',
    category: 'E-Commerce',
    description: 'An online store for kurtis, co-ord sets, suits, sarees and dupattas in block prints, chanderi and handloom cotton, made and dispatched from Amritsar.',
    highlight: 'Festive Storefront',
    imageUrl: '/portfolio/saanshikaethnics.webp',
    techStack: ['Next.js', 'React', 'Online Store', 'Wishlist & Cart'],
    websiteUrl: 'https://www.saanshikaethnics.com/',
  },
  {
    id: 'mechverses',
    title: 'Mechverses',
    category: 'Corporate',
    description: 'Catalogue website for a company trading verified second-hand machinery for the ceramic industry, built around searching the inventory and making an enquiry.',
    highlight: 'Search-Led Catalogue',
    imageUrl: '/portfolio/mechverses.webp',
    techStack: ['React', 'Tailwind CSS', 'Inventory Search'],
    websiteUrl: 'https://www.mechverses.in',
  },
  {
    id: 'arommaalfresco',
    title: 'Aromma Alfresco Events',
    category: 'Corporate',
    description: 'An elegant digital presence for premium event management and catering services, highlighting immersive outdoor experiences and beautiful venue spaces.',
    highlight: 'Elegant Experience',
    imageUrl: '/portfolio/arommaalfresco.webp',
    techStack: ['React', 'Tailwind CSS', 'Framer Motion'],
    websiteUrl: 'https://www.arommaalfresco.com/',
  },
  {
    id: 'srimahalingeshwaraalayamutrust',
    title: 'Sri Mahalingeshwara Alayamu Trust',
    category: 'Corporate',
    description: 'A dignified community portal and secure donation management framework supporting historic temple preservation and local charitable initiatives.',
    highlight: 'Meaningful Connection',
    imageUrl: '/portfolio/srimahalingeshwaraalayamutrust.webp',
    techStack: ['Vite', 'React', 'Tailwind CSS', 'Secure Payments'],
    websiteUrl: 'https://www.srimahlingeshwaraalayamutrust.com',
  },
  {
    id: 'jhorley',
    title: 'J. Horley Portfolio',
    category: 'Landing Page',
    description: 'A pristine, minimalist design showcase and digital creative portfolio featuring fluid layout mechanics and beautiful premium typography.',
    highlight: 'Pristine Aesthetics',
    imageUrl: '/portfolio/jhorley.webp',
    techStack: ['React', 'Vite', 'Motion', 'Tailwind CSS'],
    websiteUrl: 'https://www.jhorley.com/',
  },
  {
    id: 'sproutslegal',
    title: 'Sprouts Legal',
    category: 'Corporate',
    description: 'An approachable, streamlined legal consultation portal designed to simplify corporate structuring, client onboarding, and digital appointment booking.',
    highlight: 'Trust & Clarity',
    imageUrl: '/portfolio/sproutslegal.webp',
    techStack: ['Vite', 'React', 'Tailwind CSS', 'SEO Optimization'],
    websiteUrl: 'https://www.sproutslegal.com/',
  },
  {
    id: 'fawdubai',
    title: 'FAW Dubai',
    category: 'Corporate',
    description: 'Brand website for Frozen Apple Weddings, a luxury wedding design company, led by full-screen photography with a direct route to booking a consultation.',
    highlight: 'Photography First',
    imageUrl: '/portfolio/fawdubai.webp',
    techStack: ['React', 'Tailwind CSS', 'Consultation Booking'],
    websiteUrl: 'https://www.fawdubai.com/',
  },
  {
    id: 'kashmirsinthantop',
    title: 'Kashmir Sinthan Top Tour & Travel',
    category: 'Corporate',
    description: 'A fast, lightweight site for a government-registered Kashmir tour operator in Daksum, covering Sinthan Top, Dal Lake, Pahalgam, Gulmarg, Sonamarg and Gurez Valley itineraries.',
    highlight: 'Local & Fast',
    imageUrl: '/portfolio/kashmirsinthantop.webp',
    techStack: ['HTML5', 'CSS3', 'WhatsApp Booking', 'Performance Optimization'],
    websiteUrl: 'https://www.kashmirsinthantoptourandtravels.com/',
  },
  {
    id: 'bmscrubber',
    title: 'BM Scrubber',
    category: 'Corporate',
    description: 'An industrial cleaning machinery and heavy-duty automatic floor scrubber equipment B2B showcase built for high-performance product sourcing.',
    highlight: 'Corporate Authority',
    imageUrl: '/portfolio/bmscrubber.webp',
    techStack: ['React', 'Tailwind CSS', 'Product Catalog'],
    websiteUrl: 'https://www.bmscrubber.com/',
  },
  {
    id: 'medaralabs',
    title: 'Medara Labs',
    category: 'Corporate',
    description: 'Business website for a pharmaceutical marketing and distribution company, organised around its product range, quality standards and enquiries.',
    highlight: 'Products and Quality',
    imageUrl: '/portfolio/medaralabs.webp',
    techStack: ['React', 'Tailwind CSS', 'Product Filters'],
    websiteUrl: 'https://www.medaralabs.com/',
  },
  {
    id: 'fairmountphotography',
    title: 'Fairmount Photography',
    category: 'Landing Page',
    description: 'A visual-first, high-performance portfolio engineered for a premium wedding and commercial photography studio, featuring responsive galleries.',
    highlight: 'Visual Brilliance',
    imageUrl: '/portfolio/fairmountphotography.webp',
    techStack: ['React', 'Vite', 'Tailwind CSS', 'Image Optimization'],
    websiteUrl: 'https://www.fairmountphotographys.com/',
  },
  {
    id: 'modernoffset',
    title: 'Modern Offset Printers',
    category: 'Corporate',
    description: 'A state-of-the-art print and publishing portal designed for high-volume commercial printing orders, quote calculation, and file submission.',
    highlight: 'Streamlined Ordering',
    imageUrl: '/portfolio/modernoffset.webp',
    techStack: ['React', 'Vite', 'Tailwind CSS', 'Order Management'],
    websiteUrl: 'https://www.modernoffset.com/',
  },
  {
    id: 'skyfaboverseas',
    title: 'Skyfab Overseas Worldwide',
    category: 'Corporate',
    description: 'International textile exporting distribution network portal facilitating bulk supply chain communication and global custom fabrics sourcing.',
    highlight: 'Global Reach',
    imageUrl: '/portfolio/skyfaboverseas.webp',
    techStack: ['Vite', 'React', 'Tailwind CSS', 'Global SEO'],
    websiteUrl: 'https://www.skyfaboverseasworldwide.com/',
  },
  {
    id: 'hindustanflowcontrol',
    title: 'Hindustan Flow Control',
    category: 'Corporate',
    description: 'B2B commercial catalog and specification tracker for premium industrial flow valves and mechanical piping systems distribution.',
    highlight: 'Technical Precision',
    imageUrl: '/portfolio/hindustanflowcontrol.webp',
    techStack: ['React', 'Vite', 'Tailwind CSS', 'Spec Catalog'],
    websiteUrl: 'https://www.hindustanflowcontrol.com/',
  },
  {
    id: 'fihmonline',
    title: 'FIHM Online Hospitality',
    category: 'SaaS',
    description: 'A state-of-the-art learning management hub and vocational training academy curriculum portal for elite hotel and hospitality studies.',
    highlight: 'Intuitive Flow',
    imageUrl: '/portfolio/fihmonline.webp',
    techStack: ['React', 'Tailwind CSS', 'LMS Navigation', 'Vite'],
    websiteUrl: 'https://www.fihmonline.com/',
  },
  {
    id: 'spellzee',
    title: 'Spellzee',
    category: 'Corporate',
    description: 'Site for an IITM-incubated phonics and language learning platform running live classes that build reading, writing and speaking skills for children aged 4 to 14.',
    highlight: 'Playful Learning',
    imageUrl: '/portfolio/spellzee.webp',
    techStack: ['WordPress', 'Elementor', 'Demo Booking', 'SEO Optimization'],
    websiteUrl: 'https://spellzee.in/',
  },
  {
    id: 'adarshgyanniketan',
    title: 'Adarsh Gyan Niketan',
    category: 'Corporate',
    description: 'A school website for a co-educational primary and middle school in Shahpur, Bhojpur, Bihar, running since 1998, covering academics, admissions, faculty, facilities and gallery.',
    highlight: 'Admissions Open',
    imageUrl: '/portfolio/adarshgyanniketan.webp',
    techStack: ['Next.js', 'React', 'Admissions Enquiries', 'Local SEO'],
    websiteUrl: 'https://www.adarshgyanniketan.com/',
  },
  {
    id: 'southdelhiflats',
    title: 'South Delhi Flats & Floors',
    category: 'Corporate',
    description: 'A luxury real estate site for builder floors, apartments and independent houses in Defence Colony, Greater Kailash, Panchsheel Park and other prime South Delhi neighbourhoods.',
    highlight: 'Luxury Listings',
    imageUrl: '/portfolio/southdelhiflats.webp',
    techStack: ['Vite', 'React', 'Property Listings', 'Local SEO'],
    websiteUrl: 'https://www.southdelhiflats.com/',
  },
];
